export const IncidentModel = {
  description: '',
  incident_date: '',
  incident_time: '',
  injuries: '',
  note: '',
  on_duty: false,
  region: '',
  reported_to: '',
  responsible: '',
  street: '',
  weapons_used: [],
  last_modify_user: 1,
  primary_person: {
    agency: '',
    contact: '',
    date_of_birth: '',
    first_name: '',
    gender: '',
    index_number: null,
    job_title: '',
    last_name: '',
    name: '',
    nationality: null,
    title: '',
    type_of_contract: '',
    un_official: false
  },
  reported: false,
  submitted_by: 1,
  status: 'submitted'
};
