version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:8-browsers
        environment:
          RELEASE_MATCH: "release/*"
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - deps-v1-{{ checksum "package-lock.json" }}

      - checkout
      - run:
          name: setup
          command: |
            npm install polymer-cli
            npm install

      - run:
          name: build
          command: |
            npm run build

      - run:
          name: test
          command: |
            export PATH=$PWD/node_modules/.bin:$PATH

            sudo apt-get remove firefox-mozilla-build binutils
            sudo sh -c "echo 'deb http://ftp.hr.debian.org/debian sid main' >> /etc/apt/sources.list"
            sudo apt-get update
            sudo apt-get install -t sid firefox
            firefox --version

            xvfb-run -a polymer test --skip-selenium-install

      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - save_cache:
          key: deps-v1-{{ checksum "package-lock.json" }}
          paths:
            - "./node_modules"

      - deploy:
          name: tag and release if release candidate
          command: |
              if [[ $CIRCLE_BRANCH == $RELEASE_MATCH ]]; then
                curl --user ${CIRCLE_TOKEN}: \
                  --fail '
                  --data build_parameters[CIRCLE_JOB]=tag \
                  --data revision=$CIRCLE_SHA1 \
                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              else
                echo "Skipped as '$CIRCLE_BRANCH' does not match '$RELEASE_MATCH' branch"
              fi
  tag:
    docker:
      - image: circleci/node:8
        environment:
          API_URL: https://api.github.com/repos/unicef/sir-poc-fe
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ab:c9:0f:60:bb:e1:6e:73:ec:af:82:2c:3c:13:9e:d2"
      - run:
          name: package and release
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            export TAG=${TAG:=${CIRCLE_BRANCH#*/}}
            git status
            git show-branch release/$TAG
            if [ $? -gt 0 ];then
              git reset --hard

              git config user.email "ci@unicef.org"
              git config user.name "CI"

              git checkout master
              git merge --no-ff release/$TAG -m "merge release/$TAG"
              git tag -a -m "v$TAG" $TAG
              git checkout develop
              git merge --no-ff release/$TAG -m "merge release/$TAG"
              git push --verbose --all
              git push --verbose --tags
              git push origin --verbose --delete release/$TAG
            fi
      - run:
          name: release
          command: |
            export TAG=${TAG:=${CIRCLE_BRANCH#*/}}
            echo
            export TODAY=`date '+%d %B %Y at %H:%M'`
            function is_pre()
            {
                [[ "$(echo "$TAG" | sed 's/[0-9.]//g')" == "" ]] && echo false || echo true
            }
            function data() {
            cat <<EOF
            { "tag_name": "$TAG",
              "name": "v$TAG",
              "body": "version $TAG - Built on $TODAY",
              "draft": false,
              "prerelease": $(is_pre)
            }
            EOF
            }
            data=$(data)
            curl -X POST -s \
              --fail --verbose \
              -H "Accept: application/json" \
              -H "Content-Type:application/json" \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              ${API_URL}/releases \
              -d "$data"
      - deploy:
          name: dockerize
          command: |
              if [[ $CIRCLE_BRANCH == $RELEASE_MATCH ]]; then
                curl --user ${CIRCLE_TOKEN}: \
                  --fail \
                  --data build_parameters[TAG]=$TAG \
                  --data build_parameters[JOB]=frontend \
                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/sir-releases/tree/develop
              else
                echo "Skipped as '$CIRCLE_BRANCH' does not match '$RELEASE_MATCH' branch"
              fi
